### ISSUE TITLE
User Story 1

### ISSUE THREAD

**Issue by BenMaharjan** [SchoolOfCode/bc17-w5d1-catch-up-express-api-with-file-storage-it-s-not-a-bug-it-s-a-feature#1]
```[tasklist]
### Tasks
- [x] Create a GET request with the endpoint '/api/recipes'
- [x] Create a GET request with the endpoint 'api/recipes/:id'
- [x] Create a POST request with the endpoint 'api/recipes'
- [ ] Create a PATCH request with the endpoint api/recipes/:id
- [ ] Create a DELETE request with the endpoint api/recipes/:id
```
